"""Type stubs for the somtparser package."""

from enum import Enum
from fractions import Fraction
from typing import Iterator, List, Mapping, Optional, Sequence, Tuple, Union

__version__: str

_IntLike = Union[int, str]
_Value = Union[bool, int, float, Fraction, str, None]

class ParseError(Exception): ...

class ResultType(Enum):
    SAT: ResultType
    UNSAT: ResultType
    DELTA_SAT: ResultType
    UNKNOWN: ResultType
    ERROR: ResultType

class OptKind(Enum):
    MINIMIZE: OptKind
    MAXIMIZE: OptKind
    MAXSAT: OptKind
    MINSAT: OptKind
    LEX: OptKind
    PARETO: OptKind
    BOX: OptKind
    MINMAX: OptKind
    MAXMIN: OptKind
    NONE: OptKind

class CmdType(Enum):
    UNKNOWN: CmdType
    EOF: CmdType
    ASSERT: CmdType
    CHECK_SAT: CmdType
    CHECK_SAT_ASSUMING: CmdType
    DECLARE_CONST: CmdType
    DECLARE_FUN: CmdType
    DECLARE_SORT: CmdType
    DECLARE_DATATYPES: CmdType
    DEFINE_FUN: CmdType
    DEFINE_FUN_REC: CmdType
    DEFINE_FUNS_REC: CmdType
    DEFINE_SORT: CmdType
    ECHO: CmdType
    EXIT: CmdType
    GET_ASSERTIONS: CmdType
    GET_ASSIGNMENT: CmdType
    GET_INFO: CmdType
    GET_MODEL: CmdType
    GET_OPTION: CmdType
    GET_PROOF: CmdType
    GET_UNSAT_ASSUMPTIONS: CmdType
    GET_UNSAT_CORE: CmdType
    GET_VALUE: CmdType
    POP: CmdType
    PUSH: CmdType
    RESET: CmdType
    RESET_ASSERTIONS: CmdType
    SET_INFO: CmdType
    SET_LOGIC: CmdType
    SET_OPTION: CmdType
    EXISTS: CmdType
    FORALL: CmdType
    GET_OBJECTIVES: CmdType
    ASSERT_SOFT: CmdType
    DEFINE_OBJ: CmdType
    DEFINE_MIN_OBJ: CmdType
    DEFINE_MAX_OBJ: CmdType
    MINIMIZE: CmdType
    MAXIMIZE: CmdType
    LEX_OPTIMIZE: CmdType
    PARETO_OPTIMIZE: CmdType
    BOX_OPTIMIZE: CmdType
    MINMAX: CmdType
    MAXMIN: CmdType
    MAXSAT: CmdType
    MINSAT: CmdType
    OPTIMIZE: CmdType

class Sort:
    @property
    def name(self) -> str: ...
    @property
    def arity(self) -> int: ...
    @property
    def is_bool(self) -> bool: ...
    @property
    def is_int(self) -> bool: ...
    @property
    def is_real(self) -> bool: ...
    @property
    def is_int_or_real(self) -> bool: ...
    @property
    def is_bv(self) -> bool: ...
    @property
    def is_fp(self) -> bool: ...
    @property
    def is_string(self) -> bool: ...
    @property
    def is_regex(self) -> bool: ...
    @property
    def is_array(self) -> bool: ...
    @property
    def is_datatype(self) -> bool: ...
    @property
    def is_rounding_mode(self) -> bool: ...
    @property
    def is_uninterpreted(self) -> bool: ...
    @property
    def bv_width(self) -> int: ...
    @property
    def fp_exponent_width(self) -> int: ...
    @property
    def fp_significand_width(self) -> int: ...
    @property
    def index_sort(self) -> Optional[Sort]: ...
    @property
    def elem_sort(self) -> Optional[Sort]: ...

class Node:
    @property
    def kind(self) -> str: ...
    @property
    def sort(self) -> Sort: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> _Value: ...
    @property
    def num_children(self) -> int: ...
    @property
    def children(self) -> List[Node]: ...
    @property
    def bit_width(self) -> int: ...
    @property
    def is_const(self) -> bool: ...
    @property
    def is_var(self) -> bool: ...
    @property
    def is_leaf(self) -> bool: ...
    @property
    def is_internal(self) -> bool: ...
    @property
    def is_err(self) -> bool: ...
    @property
    def is_null(self) -> bool: ...
    @property
    def is_unknown(self) -> bool: ...
    @property
    def is_atom(self) -> bool: ...
    @property
    def is_literal(self) -> bool: ...
    @property
    def is_true(self) -> bool: ...
    @property
    def is_false(self) -> bool: ...
    @property
    def is_and(self) -> bool: ...
    @property
    def is_or(self) -> bool: ...
    @property
    def is_not(self) -> bool: ...
    @property
    def is_implies(self) -> bool: ...
    @property
    def is_xor(self) -> bool: ...
    @property
    def is_ite(self) -> bool: ...
    @property
    def is_eq(self) -> bool: ...
    @property
    def is_distinct(self) -> bool: ...
    @property
    def is_add(self) -> bool: ...
    @property
    def is_sub(self) -> bool: ...
    @property
    def is_mul(self) -> bool: ...
    @property
    def is_neg(self) -> bool: ...
    @property
    def is_div_int(self) -> bool: ...
    @property
    def is_div_real(self) -> bool: ...
    @property
    def is_mod(self) -> bool: ...
    @property
    def is_le(self) -> bool: ...
    @property
    def is_lt(self) -> bool: ...
    @property
    def is_ge(self) -> bool: ...
    @property
    def is_gt(self) -> bool: ...
    @property
    def is_arith_op(self) -> bool: ...
    @property
    def is_arith_comp(self) -> bool: ...
    @property
    def is_arith_term(self) -> bool: ...
    @property
    def is_const_bool(self) -> bool: ...
    @property
    def is_const_int(self) -> bool: ...
    @property
    def is_const_real(self) -> bool: ...
    @property
    def is_const_bv(self) -> bool: ...
    @property
    def is_const_fp(self) -> bool: ...
    @property
    def is_const_str(self) -> bool: ...
    @property
    def is_numeral(self) -> bool: ...
    @property
    def is_pi(self) -> bool: ...
    @property
    def is_e(self) -> bool: ...
    @property
    def is_infinity(self) -> bool: ...
    @property
    def is_nan(self) -> bool: ...
    @property
    def is_epsilon(self) -> bool: ...
    @property
    def is_bv_op(self) -> bool: ...
    @property
    def is_bv_term(self) -> bool: ...
    @property
    def is_bv_atom(self) -> bool: ...
    @property
    def is_fp_op(self) -> bool: ...
    @property
    def is_fp_term(self) -> bool: ...
    @property
    def is_fp_atom(self) -> bool: ...
    @property
    def is_str_op(self) -> bool: ...
    @property
    def is_str_atom(self) -> bool: ...
    @property
    def is_select(self) -> bool: ...
    @property
    def is_store(self) -> bool: ...
    @property
    def is_const_array(self) -> bool: ...
    @property
    def is_array(self) -> bool: ...
    @property
    def is_let(self) -> bool: ...
    @property
    def is_let_chain(self) -> bool: ...
    @property
    def is_quant_var(self) -> bool: ...
    @property
    def is_temp_var(self) -> bool: ...
    @property
    def is_uf_application(self) -> bool: ...
    @property
    def is_func_def(self) -> bool: ...
    @property
    def is_func_dec(self) -> bool: ...
    @property
    def is_func_application(self) -> bool: ...
    def to_smt2(self) -> str: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Node: ...
    def __iter__(self) -> Iterator[Node]: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

class Model:
    def __init__(self) -> None: ...
    def __getitem__(self, name: str) -> Node: ...
    def __contains__(self, name: str) -> bool: ...
    def __len__(self) -> int: ...
    def get(self, name: str, default: object = ...) -> object: ...
    def add(self, name: str, value: Node) -> None: ...
    def keys(self) -> List[str]: ...
    def values(self) -> List[Node]: ...
    def items(self) -> List[Tuple[str, Node]]: ...
    @property
    def is_empty(self) -> bool: ...

class MetaObjective:
    @property
    def kind(self) -> OptKind: ...
    @property
    def group_id(self) -> str: ...
    @property
    def is_minimize(self) -> bool: ...
    @property
    def is_maximize(self) -> bool: ...
    @property
    def is_maxsat(self) -> bool: ...
    @property
    def is_minsat(self) -> bool: ...
    @property
    def is_lex(self) -> bool: ...
    @property
    def is_pareto(self) -> bool: ...
    @property
    def is_box(self) -> bool: ...
    @property
    def is_single(self) -> bool: ...
    @property
    def is_multi(self) -> bool: ...
    @property
    def term(self) -> Optional[Node]: ...
    @property
    def num_subobjectives(self) -> int: ...
    def subobjective(self, index: int) -> MetaObjective: ...
    @property
    def subobjectives(self) -> List[MetaObjective]: ...

class Objective(MetaObjective): ...

class Command:
    @property
    def type(self) -> CmdType: ...
    @property
    def line_number(self) -> int: ...
    @property
    def expr(self) -> Optional[Node]: ...
    @property
    def name(self) -> str: ...
    @property
    def sort(self) -> Optional[Sort]: ...
    @property
    def params(self) -> List[Node]: ...
    @property
    def group_id(self) -> str: ...
    @property
    def weight(self) -> Optional[Node]: ...
    @property
    def push_pop_level(self) -> int: ...
    @property
    def logic(self) -> str: ...
    @property
    def value_terms(self) -> List[Node]: ...
    @property
    def keyword(self) -> str: ...
    @property
    def is_assert(self) -> bool: ...
    @property
    def is_push(self) -> bool: ...
    @property
    def is_pop(self) -> bool: ...
    @property
    def is_reset(self) -> bool: ...
    @property
    def is_reset_assertions(self) -> bool: ...

class Script:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Command: ...
    def __iter__(self) -> Iterator[Command]: ...
    @property
    def commands(self) -> List[Command]: ...

class Parser:
    def __init__(self) -> None: ...
    # Parsing
    def parse_file(self, path: str) -> Parser: ...
    def parse_string(self, text: str) -> Parser: ...
    def assert_(self, constraint: Union[str, Node]) -> None: ...
    def expr(self, text: str) -> Node: ...
    def parse_model(self, text: str, only_declared: bool = ...) -> Model: ...
    # Contents
    @property
    def assertions(self) -> List[Node]: ...
    @property
    def assumptions(self) -> List[List[Node]]: ...
    @property
    def soft_assertions(self) -> List[Node]: ...
    @property
    def soft_weights(self) -> List[Node]: ...
    @property
    def grouped_assertions(self) -> Mapping[str, set]: ...
    @property
    def grouped_soft_assertions(self) -> Mapping[str, set]: ...
    @property
    def objectives(self) -> List[Objective]: ...
    @property
    def variables(self) -> List[Node]: ...
    @property
    def declared_variables(self) -> List[Node]: ...
    @property
    def functions(self) -> List[Node]: ...
    @property
    def logic(self) -> str: ...
    @property
    def script(self) -> Script: ...
    @property
    def result_type(self) -> ResultType: ...
    def check_sat(self) -> ResultType: ...
    @property
    def node_count(self) -> int: ...
    def get_model(self) -> Optional[Model]: ...
    def get_variable(self, name: str) -> Node: ...
    def is_declared_variable(self, name: str) -> bool: ...
    def is_declared_function(self, name: str) -> bool: ...
    # Options
    def set_option(self, key: str, value: Union[str, bool, int, float]) -> None: ...
    def options_smt2(self) -> str: ...
    def set_strict_smtlib(self, strict: bool) -> None: ...
    def get_strict_smtlib(self) -> bool: ...
    def set_evaluate_precision(self, precision: int) -> None: ...
    def set_evaluate_use_floating(self, use_floating: bool) -> None: ...
    def get_evaluate_use_floating(self) -> bool: ...
    def set_command_logging(self, enable: bool) -> None: ...
    # Incremental
    def push(self, n: int = ...) -> None: ...
    def pop(self, n: int = ...) -> None: ...
    def reset(self) -> None: ...
    def reset_assertions(self) -> None: ...
    # Sorts
    def int_sort(self) -> Sort: ...
    def real_sort(self) -> Sort: ...
    def bool_sort(self) -> Sort: ...
    def string_sort(self) -> Sort: ...
    def regex_sort(self) -> Sort: ...
    def rounding_mode_sort(self) -> Sort: ...
    def bv_sort(self, width: int) -> Sort: ...
    def fp_sort(self, exponent: int, significand: int) -> Sort: ...
    def array_sort(self, index: Sort, elem: Sort) -> Sort: ...
    def declare_sort(self, name: str, arity: int) -> Sort: ...
    def define_sort(self, name: str, params: Sequence[Sort], out_sort: Sort) -> Sort: ...
    # Variables
    def declare_var(self, name: str, sort: Union[str, Sort]) -> Node: ...
    def var_bool(self, name: str) -> Node: ...
    def var_int(self, name: str) -> Node: ...
    def var_real(self, name: str) -> Node: ...
    def var_bv(self, name: str, width: int) -> Node: ...
    def var_fp(self, name: str, exponent: int, significand: int) -> Node: ...
    def var_str(self, name: str) -> Node: ...
    def var_array(self, name: str, index: Sort, elem: Sort) -> Node: ...
    def var_rounding_mode(self, name: str) -> Node: ...
    def quant_var(self, name: str, sort: Sort) -> Node: ...
    # Constants
    def true_(self) -> Node: ...
    def false_(self) -> Node: ...
    def const_int(self, value: _IntLike) -> Node: ...
    def const_real(self, value: Union[float, int, str]) -> Node: ...
    def const_str(self, value: str) -> Node: ...
    def const_bv(self, value: _IntLike, width: int) -> Node: ...
    def const_fp(self, value: str, exponent: int, significand: int) -> Node: ...
    def rounding_mode(self, mode: str) -> Node: ...
    def pi(self) -> Node: ...
    def e(self) -> Node: ...
    def epsilon(self) -> Node: ...
    def nan(self) -> Node: ...
    def infinity(self, sort: Sort) -> Node: ...
    def pos_infinity(self) -> Node: ...
    def neg_infinity(self) -> Node: ...
    def const_array(self, sort: Sort, value: Node) -> Node: ...
    # Boolean
    def not_(self, a: Node) -> Node: ...
    def and_(self, a: Union[Node, Sequence[Node]], b: Optional[Node] = ...) -> Node: ...
    def or_(self, a: Union[Node, Sequence[Node]], b: Optional[Node] = ...) -> Node: ...
    def implies(self, a: Node, b: Node) -> Node: ...
    def xor_(self, a: Union[Node, Sequence[Node]], b: Optional[Node] = ...) -> Node: ...
    def ite(self, cond: Node, then_: Node, else_: Node) -> Node: ...
    def eq(self, a: Union[Node, Sequence[Node]], b: Optional[Node] = ...) -> Node: ...
    def distinct(self, a: Union[Node, Sequence[Node]], b: Optional[Node] = ...) -> Node: ...
    # Arithmetic
    def add(self, a: Union[Node, Sequence[Node]], b: Optional[Node] = ...) -> Node: ...
    def sub(self, a: Union[Node, Sequence[Node]], b: Optional[Node] = ...) -> Node: ...
    def mul(self, a: Union[Node, Sequence[Node]], b: Optional[Node] = ...) -> Node: ...
    def neg(self, a: Node) -> Node: ...
    def div(self, a: Node, b: Node) -> Node: ...
    def div_int(self, a: Node, b: Node) -> Node: ...
    def div_real(self, a: Node, b: Node) -> Node: ...
    def mod(self, a: Node, b: Node) -> Node: ...
    def abs_(self, a: Node) -> Node: ...
    def pow(self, a: Node, b: Node) -> Node: ...
    def pow2(self, a: Node) -> Node: ...
    def sqrt(self, a: Node) -> Node: ...
    def safe_sqrt(self, a: Node) -> Node: ...
    def ceil(self, a: Node) -> Node: ...
    def floor(self, a: Node) -> Node: ...
    def round(self, a: Node) -> Node: ...
    def exp(self, a: Node) -> Node: ...
    def ln(self, a: Node) -> Node: ...
    def lg(self, a: Node) -> Node: ...
    def lb(self, a: Node) -> Node: ...
    def log(self, base: Node, a: Node) -> Node: ...
    def sin(self, a: Node) -> Node: ...
    def cos(self, a: Node) -> Node: ...
    def tan(self, a: Node) -> Node: ...
    def cot(self, a: Node) -> Node: ...
    def sec(self, a: Node) -> Node: ...
    def csc(self, a: Node) -> Node: ...
    def asin(self, a: Node) -> Node: ...
    def acos(self, a: Node) -> Node: ...
    def atan(self, a: Node) -> Node: ...
    def atan2(self, y: Node, x: Node) -> Node: ...
    def sinh(self, a: Node) -> Node: ...
    def cosh(self, a: Node) -> Node: ...
    def tanh(self, a: Node) -> Node: ...
    def asinh(self, a: Node) -> Node: ...
    def acosh(self, a: Node) -> Node: ...
    def atanh(self, a: Node) -> Node: ...
    def gcd(self, a: Node, b: Node) -> Node: ...
    def lcm(self, a: Node, b: Node) -> Node: ...
    def factorial(self, a: Node) -> Node: ...
    def max_(self, args: Sequence[Node]) -> Node: ...
    def min_(self, args: Sequence[Node]) -> Node: ...
    def le(self, a: Union[Node, Sequence[Node]], b: Optional[Node] = ...) -> Node: ...
    def lt(self, a: Union[Node, Sequence[Node]], b: Optional[Node] = ...) -> Node: ...
    def ge(self, a: Union[Node, Sequence[Node]], b: Optional[Node] = ...) -> Node: ...
    def gt(self, a: Union[Node, Sequence[Node]], b: Optional[Node] = ...) -> Node: ...
    def to_int(self, a: Node) -> Node: ...
    def to_real(self, a: Node) -> Node: ...
    def is_int_pred(self, a: Node) -> Node: ...
    def is_divisible(self, a: Node, b: Node) -> Node: ...
    def is_prime(self, a: Node) -> Node: ...
    def is_even(self, a: Node) -> Node: ...
    def is_odd(self, a: Node) -> Node: ...
    # BitVectors
    def bv_not(self, a: Node) -> Node: ...
    def bv_and(self, a: Node, b: Node) -> Node: ...
    def bv_or(self, a: Node, b: Node) -> Node: ...
    def bv_xor(self, a: Node, b: Node) -> Node: ...
    def bv_nand(self, a: Node, b: Node) -> Node: ...
    def bv_nor(self, a: Node, b: Node) -> Node: ...
    def bv_xnor(self, a: Node, b: Node) -> Node: ...
    def bv_comp(self, a: Node, b: Node) -> Node: ...
    def bv_neg(self, a: Node) -> Node: ...
    def bv_add(self, a: Node, b: Node) -> Node: ...
    def bv_sub(self, a: Node, b: Node) -> Node: ...
    def bv_mul(self, a: Node, b: Node) -> Node: ...
    def bv_udiv(self, a: Node, b: Node) -> Node: ...
    def bv_urem(self, a: Node, b: Node) -> Node: ...
    def bv_sdiv(self, a: Node, b: Node) -> Node: ...
    def bv_srem(self, a: Node, b: Node) -> Node: ...
    def bv_smod(self, a: Node, b: Node) -> Node: ...
    def bv_shl(self, a: Node, b: Node) -> Node: ...
    def bv_lshr(self, a: Node, b: Node) -> Node: ...
    def bv_ashr(self, a: Node, b: Node) -> Node: ...
    def bv_concat(self, args: Sequence[Node]) -> Node: ...
    def bv_extract(self, a: Node, high: int, low: int) -> Node: ...
    def bv_repeat(self, a: Node, count: int) -> Node: ...
    def bv_zero_extend(self, a: Node, count: int) -> Node: ...
    def bv_sign_extend(self, a: Node, count: int) -> Node: ...
    def bv_rotate_left(self, a: Node, count: int) -> Node: ...
    def bv_rotate_right(self, a: Node, count: int) -> Node: ...
    def bv_ult(self, a: Node, b: Node) -> Node: ...
    def bv_ule(self, a: Node, b: Node) -> Node: ...
    def bv_ugt(self, a: Node, b: Node) -> Node: ...
    def bv_uge(self, a: Node, b: Node) -> Node: ...
    def bv_slt(self, a: Node, b: Node) -> Node: ...
    def bv_sle(self, a: Node, b: Node) -> Node: ...
    def bv_sgt(self, a: Node, b: Node) -> Node: ...
    def bv_sge(self, a: Node, b: Node) -> Node: ...
    def bv_to_nat(self, a: Node) -> Node: ...
    def bv_to_int(self, a: Node) -> Node: ...
    def int_to_bv(self, a: Node, width: int) -> Node: ...
    def nat_to_bv(self, a: Node, width: int) -> Node: ...
    # Floating point
    def fp_add(self, rm: Node, a: Node, b: Node) -> Node: ...
    def fp_sub(self, rm: Node, a: Node, b: Node) -> Node: ...
    def fp_mul(self, rm: Node, a: Node, b: Node) -> Node: ...
    def fp_div(self, rm: Node, a: Node, b: Node) -> Node: ...
    def fp_fma(self, rm: Node, a: Node, b: Node, c: Node) -> Node: ...
    def fp_abs(self, a: Node) -> Node: ...
    def fp_neg(self, a: Node) -> Node: ...
    def fp_rem(self, a: Node, b: Node) -> Node: ...
    def fp_sqrt(self, rm: Node, a: Node) -> Node: ...
    def fp_round_to_integral(self, rm: Node, a: Node) -> Node: ...
    def fp_min(self, a: Node, b: Node) -> Node: ...
    def fp_max(self, a: Node, b: Node) -> Node: ...
    def fp_le(self, a: Node, b: Node) -> Node: ...
    def fp_lt(self, a: Node, b: Node) -> Node: ...
    def fp_ge(self, a: Node, b: Node) -> Node: ...
    def fp_gt(self, a: Node, b: Node) -> Node: ...
    def fp_eq(self, a: Node, b: Node) -> Node: ...
    def fp_is_normal(self, a: Node) -> Node: ...
    def fp_is_subnormal(self, a: Node) -> Node: ...
    def fp_is_zero(self, a: Node) -> Node: ...
    def fp_is_inf(self, a: Node) -> Node: ...
    def fp_is_nan(self, a: Node) -> Node: ...
    def fp_is_neg(self, a: Node) -> Node: ...
    def fp_is_pos(self, a: Node) -> Node: ...
    def fp_to_real(self, a: Node) -> Node: ...
    def fp_to_ubv(self, rm: Node, a: Node, width: int) -> Node: ...
    def fp_to_sbv(self, rm: Node, a: Node, width: int) -> Node: ...
    def to_fp(self, exponent: int, significand: int, rm: Node, a: Node) -> Node: ...
    def fp_const_from_bv(self, sign: Node, exponent: Node, mantissa: Node) -> Node: ...
    # Arrays
    def select(self, array: Node, index: Node) -> Node: ...
    def store(self, array: Node, index: Node, value: Node) -> Node: ...
    # Strings
    def str_len(self, a: Node) -> Node: ...
    def str_concat(self, args: Sequence[Node]) -> Node: ...
    def str_substr(self, s: Node, offset: Node, length: Node) -> Node: ...
    def str_prefixof(self, a: Node, b: Node) -> Node: ...
    def str_suffixof(self, a: Node, b: Node) -> Node: ...
    def str_indexof(self, s: Node, sub: Node, offset: Node) -> Node: ...
    def str_at(self, s: Node, index: Node) -> Node: ...
    def str_update(self, s: Node, index: Node, value: Node) -> Node: ...
    def str_replace(self, s: Node, old: Node, new: Node) -> Node: ...
    def str_replace_all(self, s: Node, old: Node, new: Node) -> Node: ...
    def str_to_lower(self, a: Node) -> Node: ...
    def str_to_upper(self, a: Node) -> Node: ...
    def str_rev(self, a: Node) -> Node: ...
    def str_lt(self, a: Node, b: Node) -> Node: ...
    def str_le(self, a: Node, b: Node) -> Node: ...
    def str_contains(self, a: Node, b: Node) -> Node: ...
    def str_is_digit(self, a: Node) -> Node: ...
    def str_from_int(self, a: Node) -> Node: ...
    def str_to_int(self, a: Node) -> Node: ...
    def str_to_code(self, a: Node) -> Node: ...
    def str_from_code(self, a: Node) -> Node: ...
    def str_in_re(self, s: Node, r: Node) -> Node: ...
    def str_to_re(self, s: Node) -> Node: ...
    # Regular expressions
    def re_none(self) -> Node: ...
    def re_all(self) -> Node: ...
    def re_allchar(self) -> Node: ...
    def re_concat(self, args: Sequence[Node]) -> Node: ...
    def re_union(self, args: Sequence[Node]) -> Node: ...
    def re_inter(self, args: Sequence[Node]) -> Node: ...
    def re_diff(self, args: Sequence[Node]) -> Node: ...
    def re_star(self, r: Node) -> Node: ...
    def re_plus(self, r: Node) -> Node: ...
    def re_opt(self, r: Node) -> Node: ...
    def re_range(self, lo: Node, hi: Node) -> Node: ...
    def re_complement(self, r: Node) -> Node: ...
    # Quantifiers
    def forall(self, vars: Sequence[Node], body: Node) -> Node: ...
    def exists(self, vars: Sequence[Node], body: Node) -> Node: ...
    # Functions
    def declare_fun(self, name: str, param_sorts: Sequence[Sort], out_sort: Sort) -> Node: ...
    def define_fun(self, name: str, params: Sequence[Node], out_sort: Sort,
                   body: Node) -> Node: ...
    def apply_fun(self, fun: Node, args: Sequence[Node]) -> Node: ...
    def apply_uf(self, fun: Node, args: Sequence[Node]) -> Node: ...
    # Transformations
    def substitute(self, expr: Node, mapping: Mapping[str, Node]) -> Node: ...
    def replace_nodes(self, expr: Node, mapping: Mapping[Node, Node]) -> Node: ...
    def expand_let(self, expr: Node) -> Node: ...
    def negate_comp(self, atom: Node) -> Node: ...
    def flip_comp(self, atom: Node) -> Node: ...
    def arith_normalize(self, expr: Node) -> Node: ...
    def binarize_op(self, expr: Node) -> Node: ...
    def collect_vars(self, expr: Union[Node, Sequence[Node]]) -> List[Node]: ...
    def collect_atoms(self, expr: Union[Node, Sequence[Node]]) -> List[Node]: ...
    def collect_ground_atoms(self, exprs: Sequence[Node]) -> List[Node]: ...
    def collect_assignable_vars(self, expr: Node) -> List[Node]: ...
    # Normal forms
    def to_nnf(self, expr: Union[Node, Sequence[Node]]) -> Node: ...
    def to_cnf(self, expr: Union[Node, Sequence[Node]]) -> Node: ...
    def to_dnf(self, expr: Union[Node, Sequence[Node]]) -> Node: ...
    def to_tseitin_cnf(self, expr: Node) -> Tuple[Node, List[Node]]: ...
    def is_cnf(self, expr: Union[Node, Sequence[Node]]) -> bool: ...
    def cnf_atoms(self) -> List[Node]: ...
    def cnf_bool_vars(self) -> List[Node]: ...
    def cnf_atom(self, bool_var: Node) -> Optional[Node]: ...
    def cnf_bool_var(self, atom: Node) -> Optional[Node]: ...
    # Evaluation
    def evaluate(self, expr: Node, model: Model) -> Node: ...
    # Output
    def to_string(self, expr: Node) -> str: ...
    def dump_smt2(self, filename: Optional[str] = ...) -> str: ...

def parse(text: str) -> Parser: ...
def parse_file(path: str) -> Parser: ...
