"""Type stubs for somtparser module."""

from typing import Iterator, List, Tuple, Optional
from enum import Enum

class Sort:
    """SMT-LIB2 sort (type) representation."""
    
    @property
    def kind(self) -> str: ...
    @property
    def is_bool(self) -> bool: ...
    @property
    def is_int(self) -> bool: ...
    @property
    def is_real(self) -> bool: ...
    @property
    def is_bv(self) -> bool: ...
    @property
    def is_fp(self) -> bool: ...
    @property
    def is_string(self) -> bool: ...
    @property
    def is_array(self) -> bool: ...
    @property
    def bv_width(self) -> int: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class Node:
    """SMT-LIB2 expression node (DAG node)."""
    
    @property
    def kind(self) -> str: ...
    @property
    def sort(self) -> Sort: ...
    @property
    def name(self) -> str: ...
    @property
    def num_children(self) -> int: ...
    @property
    def is_const(self) -> bool: ...
    @property
    def is_var(self) -> bool: ...
    @property
    def is_leaf(self) -> bool: ...
    @property
    def is_true(self) -> bool: ...
    @property
    def is_false(self) -> bool: ...
    @property
    def is_and(self) -> bool: ...
    @property
    def is_or(self) -> bool: ...
    @property
    def is_not(self) -> bool: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Node: ...
    def __iter__(self) -> Iterator[Node]: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def to_smt2(self) -> str: ...

class Model:
    """SMT model mapping variables to values."""
    
    def __getitem__(self, name: str) -> Node: ...
    def __contains__(self, name: str) -> bool: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def keys(self) -> List[str]: ...
    def items(self) -> List[Tuple[str, Node]]: ...

class OptKind(Enum):
    """Optimization objective kind."""
    
    MINIMIZE = ...
    MAXIMIZE = ...
    MAXSAT = ...
    LEX = ...
    PARETO = ...

class Objective:
    """Optimization objective."""
    
    @property
    def kind(self) -> OptKind: ...
    @property
    def term(self) -> Node: ...
    @property
    def is_minimize(self) -> bool: ...
    @property
    def is_maximize(self) -> bool: ...

class Parser:
    """SMT-LIB2/OMT parser and expression builder."""
    
    def __init__(self) -> None: ...
    def parse(self, path: str) -> Parser: ...
    def parse_string(self, text: str) -> Parser: ...
    @property
    def assertions(self) -> List[Node]: ...
    @property
    def assumptions(self) -> List[List[Node]]: ...
    @property
    def soft_assertions(self) -> List[Node]: ...
    @property
    def objectives(self) -> List[Objective]: ...
    @property
    def variables(self) -> List[Node]: ...
    def set_option(self, key: str, value: str) -> None: ...
    def evaluate(self, node: Node, model: Model) -> Node: ...
    def var(self, name: str, sort: str) -> Node: ...
    def const_int(self, value: str) -> Node: ...
    def const_real(self, value: str) -> Node: ...
    def true_(self) -> Node: ...
    def false_(self) -> Node: ...
    def add(self, a: Node, b: Node) -> Node: ...
    def sub(self, a: Node, b: Node) -> Node: ...
    def mul(self, a: Node, b: Node) -> Node: ...
    def eq(self, a: Node, b: Node) -> Node: ...
    def lt(self, a: Node, b: Node) -> Node: ...
    def le(self, a: Node, b: Node) -> Node: ...
    def and_(self, a: Node, b: Node) -> Node: ...
    def or_(self, a: Node, b: Node) -> Node: ...
    def not_(self, a: Node) -> Node: ...
    def ite(self, cond: Node, then_: Node, else_: Node) -> Node: ...

def parse(text: str) -> Parser:
    """Parse SMT-LIB2 text and return a Parser."""
    ...

def parse_file(path: str) -> Parser:
    """Parse SMT-LIB2 file and return a Parser."""
    ...
